# Generated by Django 4.2.16 on 2024-12-17 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Barangays',
                'ordering': ['barangay_name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('sitio', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('religion', models.CharField(choices=[('ROMAN_CATHOLIC', 'Roman Catholic'), ('ISLAM', 'Islam'), ('EVANGELICAL', 'Evangelical'), ('IGLESIA_NI_CRISTO', 'Iglesia Ni Cristo'), ('PROTESTANT', 'Protestant'), ('SEVENTH_DAY_ADVENTIST', 'Seventh Day Adventist'), ('BUDDHISM', 'Buddhism'), ('HINDUISM', 'Hinduism'), ('OTHERS', 'Others')], max_length=50)),
                ('spouse_name', models.CharField(max_length=100)),
                ('spouse_occupation', models.CharField(max_length=100)),
                ('spouse_monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rhu_management.barangay')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RHUReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('QUARTERLY', 'Quarterly Report'), ('ANNUAL', 'Annual Report'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('content', models.JSONField()),
                ('summary', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrenatalCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('REQUESTED', 'Requested'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='SCHEDULED', max_length=10)),
                ('last_menstrual_period', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_initial_record', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('age_of_gestation', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('nutritional_status', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('UNDERWEIGHT', 'Underweight'), ('OVERWEIGHT', 'Overweight')], max_length=20, null=True)),
                ('birth_plan_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('NOT_STARTED', 'Not Started')], default='NOT_STARTED', max_length=20)),
                ('dental_checkup_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('SCHEDULED', 'Scheduled'), ('NOT_DONE', 'Not Done')], default='NOT_DONE', max_length=20)),
                ('dental_checkup_date', models.DateField(blank=True, null=True)),
                ('hemoglobin_count', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('urinalysis_date', models.DateField(blank=True, null=True)),
                ('cbc_date', models.DateField(blank=True, null=True)),
                ('syphilis_test_date', models.DateField(blank=True, null=True)),
                ('syphilis_result', models.CharField(blank=True, max_length=20, null=True)),
                ('hiv_test_date', models.DateField(blank=True, null=True)),
                ('hiv_result', models.CharField(blank=True, max_length=20, null=True)),
                ('hepatitis_b_test_date', models.DateField(blank=True, null=True)),
                ('hepatitis_b_result', models.CharField(blank=True, max_length=20, null=True)),
                ('stool_exam_date', models.DateField(blank=True, null=True)),
                ('stool_exam_result', models.TextField(blank=True, null=True)),
                ('acetic_acid_wash_date', models.DateField(blank=True, null=True)),
                ('acetic_acid_wash_result', models.TextField(blank=True, null=True)),
                ('tetanus_vaccine_date', models.DateField(blank=True, null=True)),
                ('syphilis_treatment', models.TextField(blank=True, null=True)),
                ('arv_treatment', models.TextField(blank=True, null=True)),
                ('bacteriuria_treatment', models.TextField(blank=True, null=True)),
                ('anemia_treatment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhu_management.patient')),
            ],
            options={
                'ordering': ['-checkup_date'],
            },
        ),
        migrations.CreateModel(
            name='PregnancyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_type', models.CharField(choices=[('NORMAL', 'Normal Delivery'), ('CS', 'Cesarean Section'), ('ASSISTED', 'Assisted Delivery')], max_length=10)),
                ('delivery_location', models.CharField(max_length=100)),
                ('birth_weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('complications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhu_management.patient')),
            ],
            options={
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESPONDED', 'Responded'), ('EN_ROUTE', 'En Route'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhu_management.patient')),
            ],
            options={
                'ordering': ['-alert_time'],
            },
        ),
    ]
