# Generated by Django 4.2.16 on 2024-12-13 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='checkup',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='rhu_management.prenatalcheckup'),
        ),
    ]
