# Generated by Django 4.2.16 on 2024-12-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0002_vitalsigns_checkup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsigns',
            name='checkup',
        ),
    ]
