# Generated by Django 4.2.16 on 2024-11-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0002_alter_barangay_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_type',
        ),
        migrations.AddField(
            model_name='prenatalcheckup',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='A+', max_length=5),
        ),
    ]
