# Generated by Django 4.2.16 on 2024-11-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0003_remove_patient_blood_type_prenatalcheckup_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenatalcheckup',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
    ]
