# Generated by Django 4.2.16 on 2024-11-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0004_alter_prenatalcheckup_blood_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
    ]
