# Generated by Django 4.2.16 on 2024-11-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0005_remove_patient_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenatalcheckup',
            name='estimated_delivery_date',
        ),
    ]
