# Generated by Django 4.2.16 on 2024-11-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0006_remove_prenatalcheckup_estimated_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyinformation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='spouse_contact',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='spouse_occupation',
        ),
        migrations.RemoveField(
            model_name='familyinformation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='spouse_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='spouse_occupation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
