# Generated by Django 4.2.16 on 2024-11-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0007_remove_familyinformation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='spouse_monthly_income',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
