# Generated by Django 4.2.16 on 2024-11-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0008_patient_spouse_monthly_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='A-', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(choices=[('ROMAN_CATHOLIC', 'Roman Catholic'), ('ISLAM', 'Islam'), ('EVANGELICAL', 'Evangelical'), ('IGLESIA_NI_CRISTO', 'Iglesia Ni Cristo'), ('PROTESTANT', 'Protestant'), ('SEVENTH_DAY_ADVENTIST', 'Seventh Day Adventist'), ('BUDDHISM', 'Buddhism'), ('HINDUISM', 'Hinduism'), ('OTHERS', 'Others')], default='ISLAM', max_length=50),
            preserve_default=False,
        ),
    ]
