# Generated by Django 4.2.16 on 2024-11-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0009_patient_blood_type_patient_religion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyInformation',
        ),
    ]
