# Generated by Django 4.2.16 on 2024-11-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0011_remove_prenatalcheckup_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenatalcheckup',
            name='compliance_status',
        ),
        migrations.AlterField(
            model_name='prenatalcheckup',
            name='last_menstrual_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prenatalcheckup',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
