# Generated by Django 4.2.16 on 2024-11-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0013_alter_prenatalcheckup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenatalcheckup',
            name='initial_blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prenatalcheckup',
            name='initial_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prenatalcheckup',
            name='initial_last_menstrual_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prenatalcheckup',
            name='initial_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prenatalcheckup',
            name='is_initial_record',
            field=models.BooleanField(default=False),
        ),
    ]
