# Generated by Django 4.2.16 on 2024-11-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0014_prenatalcheckup_initial_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESPONDED', 'Responded'), ('EN_ROUTE', 'En Route'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10),
        ),
    ]
