# Generated by Django 4.2.16 on 2024-12-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0015_alter_emergencyalert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenatalcheckup',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prenatalcheckup',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prenatalcheckup',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
