# Generated by Django 4.2.16 on 2024-12-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhu_management', '0016_prenatalcheckup_heart_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenatalcheckup',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='prenatalcheckup',
            name='respiratory_rate',
        ),
        migrations.RemoveField(
            model_name='prenatalcheckup',
            name='temperature',
        ),
    ]
